#r "nuget:canopy,2.1.5"
#r "nuget:Selenium.WebDriver.ChromeDriver,91.0.4472.10100"
#load "Extensions/BCLExtensions.fs"
#load "Extensions/CanopyExtensions.fs"
#load "Domain.fs"
#load "Scrape.fs"
#load "ParseAndEmit.fs"